# Generated by Django 5.2 on 2025-04-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='website',
            name='name',
        ),
        migrations.AddField(
            model_name='website',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated'),
        ),
    ]
