# Generated by Django 5.2 on 2025-04-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0002_rename_last_updated_product_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='updated_at',
        ),
    ]
