# Generated by Django 5.2 on 2025-04-21 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0003_remove_website_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='First added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Website name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated'),
        ),
    ]
