# Generated by Django 5.2 on 2025-04-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0004_website_created_at_website_name_website_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Product name'),
        ),
    ]
