# Generated by Django 5.2 on 2025-04-25 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Website name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='First added')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Product name')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Product Description')),
                ('url', models.URLField(verbose_name='Product URL')),
                ('image_url', models.URLField(verbose_name='Product Image URL')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product Price')),
                ('availability', models.BooleanField(default=True, verbose_name='Product availability')),
                ('category', models.CharField(choices=[('COMP', 'Components'), ('PER', 'Peripherals')], max_length=4, verbose_name='Product Category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='First scraped')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('seen', models.BooleanField(default=False)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='coreapi.website', verbose_name='Website')),
            ],
        ),
    ]
