# Generated by Django 5.2.6 on 2025-11-06 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0002_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(db_index=True, max_length=100, verbose_name='Canonical product name')),
                ('category', models.CharField(choices=[('CPU', 'Cpu'), ('GPU', 'Gpu'), ('RAM', 'Ram'), ('STORAGE', 'Storage'), ('MOTHERBOARD', 'Motherboard'), ('PSU', 'Psu'), ('CASE', 'Case')], verbose_name='Product Category')),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Starting Price')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('attributes', models.JSONField(default=dict, verbose_name='Products attributes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='First created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CPU', 'Cpu'), ('GPU', 'Gpu'), ('RAM', 'Ram'), ('STORAGE', 'Storage'), ('MOTHERBOARD', 'Motherboard'), ('PSU', 'Psu'), ('CASE', 'Case')], verbose_name='Product Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='canonical_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='coreapi.productgroup'),
        ),
    ]
