# Generated by Django 5.2.6 on 2025-11-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0004_enable_pg_trgm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgroup',
            name='attributes',
        ),
        migrations.AddField(
            model_name='productgroup',
            name='representative_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Product Group Image URL'),
        ),
    ]
